import type { ErRelationData, ErTableShapeData, LldDiagram, LldShape } from '@/types/lld'
import { sqlIdent, sqlLiteral } from './sanitize'

type TableShape = Extract<LldShape, { type: 'lldTable' }>

/**
 * PostgreSQL-flavoured DDL.
 *
 * Views are emitted after tables since they may reference them. FK constraints
 * are emitted as ALTER TABLE rather than inline, so declaration order cannot
 * produce a forward reference to a table that does not exist yet.
 */
export function toSqlDdl(diagram: LldDiagram): string {
  const tables = diagram.shapes.filter((s): s is TableShape => s.type === 'lldTable')
  const byId = new Map(tables.map((t) => [t.id, t]))

  const out: string[] = ['-- Generated by Archboard', '']

  for (const t of tables) {
    const data = t.data as ErTableShapeData
    if (data.tableKind !== 'table') continue

    const tableName = sqlIdent(data.label, 'my_table')
    out.push(`CREATE TABLE ${tableName} (`)

    const defs: string[] = []
    for (const c of data.columns) {
      const parts = [`  ${sqlIdent(c.name, 'column')} ${c.type || 'text'}`]
      if (!c.isNullable) parts.push('NOT NULL')
      if (c.isUnique && !c.isPk) parts.push('UNIQUE')
      if (c.defaultValue) {
        parts.push(`DEFAULT ${literalOrExpression(c.defaultValue)}`)
      }
      defs.push(parts.join(' '))
    }

    const pks = data.columns.filter((c) => c.isPk)
    if (pks.length > 0) {
      defs.push(`  PRIMARY KEY (${pks.map((c) => sqlIdent(c.name)).join(', ')})`)
    }

    out.push(defs.join(',\n'))
    out.push(');', '')

    for (const idx of data.indexes) {
      const cols = idx.columnIds
        .map((id) => data.columns.find((c) => c.id === id))
        .filter((c): c is NonNullable<typeof c> => Boolean(c))
        .map((c) => sqlIdent(c.name))
      if (cols.length === 0) continue
      out.push(
        `CREATE ${idx.isUnique ? 'UNIQUE ' : ''}INDEX ${sqlIdent(idx.name, 'idx')} ON ${tableName} (${cols.join(', ')});`
      )
    }
    if (data.indexes.length > 0) out.push('')
  }

  // Views last — they can depend on the tables above.
  for (const t of tables) {
    const data = t.data as ErTableShapeData
    if (data.tableKind !== 'view') continue
    const body = (data.viewQuery ?? '').trim() || `SELECT 1 AS placeholder`
    out.push(`CREATE VIEW ${sqlIdent(data.label, 'my_view')} AS`, `${body.replace(/;+\s*$/, '')};`, '')
  }

  const constraints: string[] = []
  for (const edge of diagram.edges) {
    if (edge.type !== 'lldErRelation') continue
    const data = edge.data as ErRelationData | undefined
    if (!data) continue

    const child = byId.get(edge.source)
    const parent = byId.get(edge.target)
    if (!child || !parent) continue

    const childData = child.data as ErTableShapeData
    const parentData = parent.data as ErTableShapeData
    if (childData.tableKind !== 'table' || parentData.tableKind !== 'table') continue

    const childCol = data.sourceColumnId
      ? childData.columns.find((c) => c.id === data.sourceColumnId)
      : childData.columns.find((c) => c.isFk)
    const parentCol = data.targetColumnId
      ? parentData.columns.find((c) => c.id === data.targetColumnId)
      : parentData.columns.find((c) => c.isPk)

    if (!childCol || !parentCol) continue

    const name = `fk_${sanitizeConstraint(childData.label)}_${sanitizeConstraint(childCol.name)}`
    const onDelete = data.onDelete ? ` ON DELETE ${onDeleteClause(data.onDelete)}` : ''

    constraints.push(
      `ALTER TABLE ${sqlIdent(childData.label)} ADD CONSTRAINT ${sqlIdent(name)}\n` +
        `  FOREIGN KEY (${sqlIdent(childCol.name)}) REFERENCES ${sqlIdent(parentData.label)} (${sqlIdent(parentCol.name)})${onDelete};`
    )
  }

  if (constraints.length > 0) {
    out.push('-- Foreign keys', ...constraints, '')
  }

  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n'
}

function onDeleteClause(v: NonNullable<ErRelationData['onDelete']>): string {
  switch (v) {
    case 'cascade':
      return 'CASCADE'
    case 'restrict':
      return 'RESTRICT'
    case 'set-null':
      return 'SET NULL'
    case 'no-action':
      return 'NO ACTION'
  }
}

/**
 * Bare SQL keywords and function calls pass through; anything else is quoted.
 * Keeps `now()` and `CURRENT_TIMESTAMP` working without quoting them into
 * string literals.
 */
function literalOrExpression(value: string): string {
  const v = value.trim()
  if (/^-?\d+(\.\d+)?$/.test(v)) return v
  if (/^(true|false|null)$/i.test(v)) return v.toUpperCase()
  if (/^[A-Za-z_][A-Za-z0-9_]*\s*\(.*\)$/.test(v)) return v
  if (/^CURRENT_(TIMESTAMP|DATE|TIME)$/i.test(v)) return v.toUpperCase()
  return sqlLiteral(v)
}

function sanitizeConstraint(s: string): string {
  return (
    s
      .replace(/[^A-Za-z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '')
      .toLowerCase() || 'x'
  )
}
